//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeQuik.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeQuik.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments... .
        /// </summary>
        internal static string Additional_comments {
            get {
                return ResourceManager.GetString("Additional_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have account.
        /// </summary>
        internal static string Already_have_account {
            get {
                return ResourceManager.GetString("Already_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount charged.
        /// </summary>
        internal static string Amount_charged {
            get {
                return ResourceManager.GetString("Amount_charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        internal static string Area_Code {
            get {
                return ResourceManager.GetString("Area_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeQuick service fees (incl. Tax).
        /// </summary>
        internal static string BeQuick_service_fees {
            get {
                return ResourceManager.GetString("BeQuick_service_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking history.
        /// </summary>
        internal static string Booking_history {
            get {
                return ResourceManager.GetString("Booking_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Ride.
        /// </summary>
        internal static string Cancel_Ride {
            get {
                return ResourceManager.GetString("Cancel_Ride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL THIS RIDE?.
        /// </summary>
        internal static string CANCEL_THIS_RIDE_ {
            get {
                return ResourceManager.GetString("CANCEL_THIS_RIDE?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Place.
        /// </summary>
        internal static string Confirm_Place {
            get {
                return ResourceManager.GetString("Confirm_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme.
        /// </summary>
        internal static string Confirme {
            get {
                return ResourceManager.GetString("Confirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme Payment.
        /// </summary>
        internal static string Confirme_Payment {
            get {
                return ResourceManager.GetString("Confirme_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string Contact_us {
            get {
                return ResourceManager.GetString("Contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Payment.
        /// </summary>
        internal static string Customer_Payment {
            get {
                return ResourceManager.GetString("Customer_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        internal static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        internal static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver will arrive to you in.
        /// </summary>
        internal static string Driver_will_arrive_to_you_in {
            get {
                return ResourceManager.GetString("Driver_will_arrive_to_you_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP code sent to your number.
        /// </summary>
        internal static string Enter_OTP_code_sent_to_your_number {
            get {
                return ResourceManager.GetString("Enter_OTP_code_sent_to_your_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FARE.
        /// </summary>
        internal static string FARE {
            get {
                return ResourceManager.GetString("FARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        internal static string Forget_Password {
            get {
                return ResourceManager.GetString("Forget_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        internal static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW IS YOUR TRIP.
        /// </summary>
        internal static string HOW_IS_YOUR_TRIP {
            get {
                return ResourceManager.GetString("HOW_IS_YOUR_TRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (incl. Tax).
        /// </summary>
        internal static string incl_Tax {
            get {
                return ResourceManager.GetString("incl_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the booking.
        /// </summary>
        internal static string Keep_the_booking {
            get {
                return ResourceManager.GetString("Keep_the_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minmum payment.
        /// </summary>
        internal static string Minmum_payment {
            get {
                return ResourceManager.GetString("Minmum_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        internal static string New_user {
            get {
                return ResourceManager.GetString("New_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers that cancel less get faster bookings.
        /// </summary>
        internal static string Passengers_that_cancel_less_get_faster_bookings {
            get {
                return ResourceManager.GetString("Passengers_that_cancel_less_get_faster_bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated.
        /// </summary>
        internal static string Rated {
            get {
                return ResourceManager.GetString("Rated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resend code after.
        /// </summary>
        internal static string resend_code_after {
            get {
                return ResourceManager.GetString("resend_code_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend verification code.
        /// </summary>
        internal static string Resend_verification_code {
            get {
                return ResourceManager.GetString("Resend_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingIn.
        /// </summary>
        internal static string SingIn {
            get {
                return ResourceManager.GetString("SingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingUp.
        /// </summary>
        internal static string SingUp {
            get {
                return ResourceManager.GetString("SingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        internal static string Submit_Review {
            get {
                return ResourceManager.GetString("Submit_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount the customer paid.
        /// </summary>
        internal static string The_amount_the_customer_paid {
            get {
                return ResourceManager.GetString("The_amount_the_customer_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WE FOUND YOU A DRIVER.
        /// </summary>
        internal static string WE_FOUND_YOU_A_DRIVER {
            get {
                return ResourceManager.GetString("WE_FOUND_YOU_A_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winch.
        /// </summary>
        internal static string Winch {
            get {
                return ResourceManager.GetString("Winch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Taxi.
        /// </summary>
        internal static string Yellow_Taxi {
            get {
                return ResourceManager.GetString("Yellow_Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your driver has arrived. Please be there within 5 minutes.
        /// </summary>
        internal static string Your_driver_has_arrived__Please_be_there_within_5_minutes {
            get {
                return ResourceManager.GetString("Your_driver_has_arrived._Please_be_there_within_5_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback will help us improve driving experience better.
        /// </summary>
        internal static string Your_feedback_will_help_us_improve_driving_experience_better {
            get {
                return ResourceManager.GetString("Your_feedback_will_help_us_improve_driving_experience_better", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Wallet.
        /// </summary>
        internal static string Your_Wallet {
            get {
                return ResourceManager.GetString("Your_Wallet", resourceCulture);
            }
        }
    }
}
