//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeQuik.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeQuik.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accountant.
        /// </summary>
        public static string Accountant {
            get {
                return ResourceManager.GetString("Accountant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Promo Code.
        /// </summary>
        public static string Add_Promo_Code {
            get {
                return ResourceManager.GetString("Add_Promo_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addation Fees.
        /// </summary>
        public static string Addation_Fees {
            get {
                return ResourceManager.GetString("Addation_Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments... .
        /// </summary>
        public static string Additional_comments {
            get {
                return ResourceManager.GetString("Additional_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have account.
        /// </summary>
        public static string Already_have_account {
            get {
                return ResourceManager.GetString("Already_have_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount charged.
        /// </summary>
        public static string Amount_charged {
            get {
                return ResourceManager.GetString("Amount_charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis report.
        /// </summary>
        public static string Analysis_report {
            get {
                return ResourceManager.GetString("Analysis_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Code.
        /// </summary>
        public static string Area_Code {
            get {
                return ResourceManager.GetString("Area_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrived.
        /// </summary>
        public static string Arrived {
            get {
                return ResourceManager.GetString("Arrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance code operation.
        /// </summary>
        public static string Balance_code_operation {
            get {
                return ResourceManager.GetString("Balance_code_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance operation.
        /// </summary>
        public static string Balance_operation {
            get {
                return ResourceManager.GetString("Balance_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeQuick service fees (incl. Tax).
        /// </summary>
        public static string BeQuick_service_fees {
            get {
                return ResourceManager.GetString("BeQuick_service_fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking history.
        /// </summary>
        public static string Booking_history {
            get {
                return ResourceManager.GetString("Booking_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking history is empty.
        /// </summary>
        public static string Booking_history_is_empty {
            get {
                return ResourceManager.GetString("Booking_history_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Ride.
        /// </summary>
        public static string Cancel_Ride {
            get {
                return ResourceManager.GetString("Cancel_Ride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL THIS RIDE?.
        /// </summary>
        public static string CANCEL_THIS_RIDE_ {
            get {
                return ResourceManager.GetString("CANCEL_THIS_RIDE?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Map.
        /// </summary>
        public static string Client_Map {
            get {
                return ResourceManager.GetString("Client_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Generated.
        /// </summary>
        public static string Code_Generated {
            get {
                return ResourceManager.GetString("Code_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector.
        /// </summary>
        public static string Collector {
            get {
                return ResourceManager.GetString("Collector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collector operation.
        /// </summary>
        public static string Collector_operation {
            get {
                return ResourceManager.GetString("Collector_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Place.
        /// </summary>
        public static string Confirm_Place {
            get {
                return ResourceManager.GetString("Confirm_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme.
        /// </summary>
        public static string Confirme {
            get {
                return ResourceManager.GetString("Confirme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirme Payment.
        /// </summary>
        public static string Confirme_Payment {
            get {
                return ResourceManager.GetString("Confirme_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Contact_us {
            get {
                return ResourceManager.GetString("Contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        public static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Payment.
        /// </summary>
        public static string Customer_Payment {
            get {
                return ResourceManager.GetString("Customer_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct from partner balance.
        /// </summary>
        public static string Deduct_from_partner_balance {
            get {
                return ResourceManager.GetString("Deduct_from_partner_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        public static string Driver {
            get {
                return ResourceManager.GetString("Driver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver will arrive to you in.
        /// </summary>
        public static string Driver_will_arrive_to_you_in {
            get {
                return ResourceManager.GetString("Driver_will_arrive_to_you_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration Trip.
        /// </summary>
        public static string Duration_Trip {
            get {
                return ResourceManager.GetString("Duration_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Trip.
        /// </summary>
        public static string End_Trip {
            get {
                return ResourceManager.GetString("End_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP code sent to your number.
        /// </summary>
        public static string Enter_OTP_code_sent_to_your_number {
            get {
                return ResourceManager.GetString("Enter_OTP_code_sent_to_your_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter promotion code.
        /// </summary>
        public static string Enter_promotion_code {
            get {
                return ResourceManager.GetString("Enter_promotion_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter voucher code.
        /// </summary>
        public static string Enter_voucher_code {
            get {
                return ResourceManager.GetString("Enter_voucher_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FARE.
        /// </summary>
        public static string FARE {
            get {
                return ResourceManager.GetString("FARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string Forget_Password {
            get {
                return ResourceManager.GetString("Forget_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gas.
        /// </summary>
        public static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Code.
        /// </summary>
        public static string Generate_Code {
            get {
                return ResourceManager.GetString("Generate_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW IS YOUR TRIP.
        /// </summary>
        public static string HOW_IS_YOUR_TRIP {
            get {
                return ResourceManager.GetString("HOW_IS_YOUR_TRIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string In_Progress {
            get {
                return ResourceManager.GetString("In_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (incl. Tax).
        /// </summary>
        public static string incl_Tax {
            get {
                return ResourceManager.GetString("incl_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOD.
        /// </summary>
        public static string JOD {
            get {
                return ResourceManager.GetString("JOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOD wallet.
        /// </summary>
        public static string JOD_wallet {
            get {
                return ResourceManager.GetString("JOD_wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep the booking.
        /// </summary>
        public static string Keep_the_booking {
            get {
                return ResourceManager.GetString("Keep_the_booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selected.
        /// </summary>
        public static string Language_Selected {
            get {
                return ResourceManager.GetString("Language_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let get started.
        /// </summary>
        public static string Let_get_started {
            get {
                return ResourceManager.GetString("Let_get_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Number.
        /// </summary>
        public static string License_Number {
            get {
                return ResourceManager.GetString("License_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minmum payment.
        /// </summary>
        public static string Minmum_payment {
            get {
                return ResourceManager.GetString("Minmum_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Money Collecting.
        /// </summary>
        public static string Money_Collecting {
            get {
                return ResourceManager.GetString("Money_Collecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user.
        /// </summary>
        public static string New_user {
            get {
                return ResourceManager.GetString("New_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Number.
        /// </summary>
        public static string Order_Number {
            get {
                return ResourceManager.GetString("Order_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnet ID.
        /// </summary>
        public static string Partnet_ID {
            get {
                return ResourceManager.GetString("Partnet_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers that cancel less get faster bookings.
        /// </summary>
        public static string Passengers_that_cancel_less_get_faster_bookings {
            get {
                return ResourceManager.GetString("Passengers_that_cancel_less_get_faster_bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string Phone_Number {
            get {
                return ResourceManager.GetString("Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plate Number.
        /// </summary>
        public static string Plate_Number {
            get {
                return ResourceManager.GetString("Plate_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy terms.
        /// </summary>
        public static string Privacy_terms {
            get {
                return ResourceManager.GetString("Privacy_terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoation Code is Added Successfully.
        /// </summary>
        public static string Promoation_Code_is_Added_Successfully {
            get {
                return ResourceManager.GetString("Promoation_Code_is_Added_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoation Code is Invalide Sorry.
        /// </summary>
        public static string Promoation_Code_is_Invalide_Sorry {
            get {
                return ResourceManager.GetString("Promoation_Code_is_Invalide_Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion code.
        /// </summary>
        public static string Promotion_code {
            get {
                return ResourceManager.GetString("Promotion_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated.
        /// </summary>
        public static string Rated {
            get {
                return ResourceManager.GetString("Rated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Operation.
        /// </summary>
        public static string Receive_Operation {
            get {
                return ResourceManager.GetString("Receive_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent transactions.
        /// </summary>
        public static string Recent_transactions {
            get {
                return ResourceManager.GetString("Recent_transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeem voucher.
        /// </summary>
        public static string Redeem_voucher {
            get {
                return ResourceManager.GetString("Redeem_voucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Data.
        /// </summary>
        public static string Refresh_Data {
            get {
                return ResourceManager.GetString("Refresh_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as.
        /// </summary>
        public static string Register_as {
            get {
                return ResourceManager.GetString("Register_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resend code after.
        /// </summary>
        public static string resend_code_after {
            get {
                return ResourceManager.GetString("resend_code_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend verification code.
        /// </summary>
        public static string Resend_verification_code {
            get {
                return ResourceManager.GetString("Resend_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        public static string Service_Type {
            get {
                return ResourceManager.GetString("Service_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Order Request.
        /// </summary>
        public static string Show_Order_Request {
            get {
                return ResourceManager.GetString("Show_Order_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingIn.
        /// </summary>
        public static string SingIn {
            get {
                return ResourceManager.GetString("SingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingUp.
        /// </summary>
        public static string SingUp {
            get {
                return ResourceManager.GetString("SingUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Trip.
        /// </summary>
        public static string Start_Trip {
            get {
                return ResourceManager.GetString("Start_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Review.
        /// </summary>
        public static string Submit_Review {
            get {
                return ResourceManager.GetString("Submit_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount the customer paid.
        /// </summary>
        public static string The_amount_the_customer_paid {
            get {
                return ResourceManager.GetString("The_amount_the_customer_paid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Balance.
        /// </summary>
        public static string Update_Balance {
            get {
                return ResourceManager.GetString("Update_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle License Number.
        /// </summary>
        public static string Vehicle_License_Number {
            get {
                return ResourceManager.GetString("Vehicle_License_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        public static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WE FOUND YOU A DRIVER.
        /// </summary>
        public static string WE_FOUND_YOU_A_DRIVER {
            get {
                return ResourceManager.GetString("WE_FOUND_YOU_A_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winch.
        /// </summary>
        public static string Winch {
            get {
                return ResourceManager.GetString("Winch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow Taxi.
        /// </summary>
        public static string Yellow_Taxi {
            get {
                return ResourceManager.GetString("Yellow_Taxi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to charge to get order from client.
        /// </summary>
        public static string You_have_to_charge_to_get_order_from_client {
            get {
                return ResourceManager.GetString("You_have_to_charge_to_get_order_from_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your driver has arrived. Please be there within 5 minutes.
        /// </summary>
        public static string Your_driver_has_arrived_Please_be_there_within_5_minutes {
            get {
                return ResourceManager.GetString("Your_driver_has_arrived_Please_be_there_within_5_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your feedback will help us improve driving experience better.
        /// </summary>
        public static string Your_feedback_will_help_us_improve_driving_experience_better {
            get {
                return ResourceManager.GetString("Your_feedback_will_help_us_improve_driving_experience_better", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your wallet.
        /// </summary>
        public static string Your_wallet {
            get {
                return ResourceManager.GetString("Your_wallet", resourceCulture);
            }
        }
    }
}
